version: '3.8'

services:
  discovery:
    container_name: discovery
    build:
      context: ./discovery-server
      dockerfile: dockerfile
    image: richardoj/discovery:latest
    ports:
      - 8761:8761
    environment:
      - eureka.instance.hostname=discovery
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false

  api_gateway:
    container_name: api_gateway
    build:
      context: ./api-gateway
      dockerfile: dockerfile
    image: richardoj/api_gateway:latest
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - discovery

  mysqldb_user:
    container_name: mysqldb-user
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass1234
      - MYSQL_DATABASE=user_db
    ports:
      - 3307:3306
    volumes:
      - ./mysqldb_user:/var/lib/mysql

  mysqldb_assignment:
    container_name: mysqldb-assignment
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass1234
      - MYSQL_DATABASE=assignment_db
    ports:
      - 3308:3306
    volumes:
      - ./mysqldb_assignment:/var/lib/mysql

  mysqldb_class:
    container_name: mysqldb-class
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass1234
      - MYSQL_DATABASE=class_db
    ports:
      - 3309:3306
    expose:
      - 3309
    volumes:
      - ./mysqldb_class:/var/lib/mysql

  user_service:
    container_name: user-service
    build:
      context: ./user-firebase
      dockerfile: dockerfile
    image: richardoj/user-service:latest
    restart: always
    depends_on:
      - mysqldb_user
      - discovery
      - api_gateway
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb_user:3306/user_db?useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "pass1234",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.generate-ddl" : "true",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.rabbitmq.host" : "gull-01.rmq.cloudamqp.com",
          "spring.rabbitmq.port" : "5672",
          "spring.rabbitmq.username" : "iufsajrj",
          "spring.rabbitmq.password" : "Ln67o-NHNQ3y3Y5FfhaoAAFLsoxDXru5",
          "spring.rabbitmq.virtual-host" : "iufsajrj",
          "eureka.client.serviceUrl.defaultZone" : "http://discovery:8761/eureka"
        }'

  assignment_service:
    container_name: assignment_service
    build:
      context: ./assignment-service
      dockerfile: dockerfile
    image: richardoj/assignment_service:latest
    restart: always
    depends_on:
      - mysqldb_assignment
      - discovery
      - api_gateway
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb_assignment:3306/assignment_db?useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "pass1234",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.generate-ddl" : "true",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "eureka.client.serviceUrl.defaultZone" : "http://discovery:8761/eureka"
        }'

  class_service:
    container_name: class_service
    build:
      context: ./class-service
      dockerfile: dockerfile
    image: richardoj/class_service:latest
    restart: always
    depends_on:
      - mysqldb_class
      - discovery
      - api_gateway
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb_class:3306/class_db?useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "pass1234",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.generate-ddl" : "true",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "eureka.client.serviceUrl.defaultZone" : "http://discovery:8761/eureka"
        }'